[loggers]
keys=root

[handlers]
keys=consoleHandler,fileHandler

[formatters]
keys=defaultFormatter

[logger_root]
level=DEBUG
handlers=consoleHandler,fileHandler

[handler_consoleHandler]
class=StreamHandler
level=WARNING
formatter=defaultFormatter
args=(sys.stdout,)

[handler_fileHandler]
class=FileHandler
level=DEBUG
formatter=defaultFormatter
encoding=utf-8
args=('app.log', 'a')

[formatter_defaultFormatter]
format=%(asctime)s [%(name)s] %(levelname)s: %(message)s
datefmt=%Y-%m-%d %H:%M:%S
